steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '/workspace']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '$REPO_NAME', '--image=gcr.io/$PROJECT_ID/$REPO_NAME', '--platform=managed']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
